// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arcdjfifvdhnjugxhfzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyY2RqZmlmdmRobmp1Z3hoZnpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzY4NTIsImV4cCI6MjA3MTQ1Mjg1Mn0.kFpTZ0s_XY2GApv3W7694qb88oVdITHp_oRHN25jHwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});